# Generated by Django 3.2.7 on 2021-09-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210930_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpyMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('spy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.spy')),
            ],
        ),
    ]
